// Common
const FOLLOWERS = "FOLLOWERS";
const BLACKLIST = "BLACKLIST";
const LATEST = "LATEST";
const PREVIOUS = "PREVIOUS";
const KEY = "KEY";
const MODE = "MODE";
const MEDIA = "MEDIA";
const NOW_PLAYING = "NOW_PLAYING";
const NOW_PLAYING_KEY = NOW_PLAYING + "_" + KEY;
const PLACEHOLDER = "PLACEHOLDER";
const GENRE = "GENRE";
const ALREADY_WATCHED = "ALREADY_WATCHED";
const UNEQ = "UNEQ";


const YTBASE = "YOU_TUBE.";
const YTLIVE = YTBASE + "LIVE."
const YTSTD = YTBASE + "STANDARD."
const YTCURRATED = YTBASE + "CURRATED."
module.exports.YOU_TUBE = {
	BASE: "YOU_TUBE." ,
	
	NOW_PLAYING_MODE: "YOU_TUBE.NOW_PLAYING.MODE" ,
	NOW_PLAYING_ID: "YOU_TUBE.NOW_PLAYING.ID" ,

	NP_SESSION_LIST: "YOU_TUBE.NP_SESSION_LIST" ,
	NP_SESSION_INDEX: "YOU_TUBE.NP_SESSION_INDEX" ,
	
	SKIPPED: "YOU_TUBE.SKIPPED" ,
	
	LIVE: {
		BASE: "YOU_TUBE.LIVE." ,
		LATEST: "YOU_TUBE.LIVE.LATEST" ,
		FOLLOWERS: "YOU_TUBE.LIVE.FOLLOWERS" ,
		BLACKLIST: "YOU_TUBE.LIVE.BLACKLIST" ,
		SKIPPED: "YOU_TUBE.LIVE.SKIPPED" ,
		NOW_PLAYING_ID: "YOU_TUBE.LIVE.NOW_PLAYING_ID"
	} ,
	STANDARD: {
		BASE: "YOU_TUBE.STANDARD." ,
		PLACEHOLDER: "YOU_TUBE.STANDARD.PLACEHOLDER" ,
		LATEST: "YOU_TUBE.STANDARD.LATEST",
		QUE: "YOU_TUBE.STANDARD.QUE" ,
		SKIPPED: "YOU_TUBE.STANDARD.SKIPPED" ,
		WATCHED: "YOU_TUBE.STANDARD.WATCHED"
		FOLLOWERS: "YOU_TUBE.STANDARD.FOLLOWERS" ,
		BLACKLIST: "YOU_TUBE.STANDARD.BLACKLIST" ,
		NOW_PLAYING_ID: "YOU_TUBE.STANDARD.NOW_PLAYING_ID"
	} ,
	PLAYLISTS: {
		BASE: "YOU_TUBE.PLAYLISTS." ,
		QUE: "YOU_TUBE.PLAYLISTS.QUE" ,
		SKIPPED: "YOU_TUBE.PLAYLISTS.SKIPPED" ,
		WATCHED: "YOU_TUBE.PLAYLISTS.COMPLETED" ,
	} ,
	CURRATED: {
		BASE: "YOU_TUBE.CURRATED." ,
		MAIN_LIST: "YOU_TUBE.CURRATED.MAIN_LIST" ,
		PLAYLISTS: "YOU_TUBE.CURRATED.PLAYLISTS"
	} ,
	SESSIONS: {
		LIST: "YOU_TUBE.SESSIONS.LIST" ,
		INDEX: "YOU_TUBE.SESSIONS.INDEX" ,
	}
};

const INSTAGRAM_B = "INSTAGRAM.";
module.exports.INSTAGRAM = {
	BASE: INSTAGRAM_B ,
	FOLLOWERS: INSTAGRAM_B + FOLLOWERS ,
	MEDIA: INSTAGRAM_B + MEDIA ,
	PLACEHOLDER: INSTAGRAM_B + PLACEHOLDER ,
	LATEST: INSTAGRAM_B + LATEST ,
	ALREADY_WATCHED: INSTAGRAM_B + ALREADY_WATCHED ,
};


const LOCAL_MEDIA_B = "LOCAL_MEDIA.";
const LM_ADANCE_SHOW = "ADVANCE_SHOW";
const LM_SPECIFIC_SHOW = "SPECIFIC_SHOW";
const LM_SPECIFIC_EPISODE = "SPECIFIC_EPISODE";
const LIVE = "LIVE.";
const LAST_SS_B = "LAST_SS.";
const LAST_SS_LM_B = LAST_SS_B + LOCAL_MEDIA_B;
const CONFIG_B = "CONFIG.";
const CONFIG_NP_B = CONFIG_B + LOCAL_MEDIA_B + LIVE;

module.exports.LOCAL_MEDIA = {
	BASE: "LOCAL_MEDIA." ,
	HD_BASE: "HARD_DRIVE." ,
	MOUNT_POINT: "HARD_DRIVE.MOUNT_POINT" ,
	CONFIG: {
		BASE: "CONFIG." ,
		GENRE: "CONFIG.LOCAL_MEDIA.LIVE.GENRE" ,
		ADVANCE_SHOW: "CONFIG.LOCAL_MEDIA.LIVE.ADVANCE_SHOW" , 
		SPECIFIC_SHOW: "CONFIG.LOCAL_MEDIA.LIVE.SPECIFIC_SHOW" ,
		SPECIFIC_EPISODE: "CONFIG.LOCAL_MEDIA.LIVE.SPECIFIC_EPISODE" ,
	} ,
	LAST_SS: {
		BASE: "LAST_SS.LOCAL_MEDIA." ,
		NOW_PLAYING_GLOBAL: "LAST_SS.LOCAL_MEDIA.GLOBAL.NOW_PLAYING" ,
		NOW_PLAYING: {
			"Odyssey": "LAST_SS.LOCAL_MEDIA.Odyssey.NOW_PLAYING" ,
			"TVShows": "LAST_SS.LOCAL_MEDIA.TVShows.NOW_PLAYING" ,
			"Movies": "LAST_SS.LOCAL_MEDIA.Movies.NOW_PLAYING" ,
			"AudioBooks": "LAST_SS.LOCAL_MEDIA.AudioBooks.NOW_PLAYING" ,
		}
	}
};

module.exports.STATUS = [
	"STATUS.USB_BUTTONS" ,
	"STATUS.LOCAL_MEDIA" ,
	"STATUS.YT_LIVE" ,
	"STATUS.TY_STANDARD" ,
	"STATUS.TWITCH" ,
	"STATUS.SKYPE" ,
	"STATUS.MOPIDY" ,
	"STATUS.DISCORD" ,
];